x-kafka-env: &kafka-env
  KAFKA_ENABLE_KRAFT: "yes"
  KAFKA_CFG_PROCESS_ROLES: "broker,controller"
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093,4@kafka-4:9093"
  KAFKA_KRAFT_CLUSTER_ID: 1
  ALLOW_PLAINTEXT_LISTENER: "yes"
  # Для двух баллов конфиг
  KAFKA_CFG_NUM_PARTITIONS: 4
  KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_CFG_MIN_INSYNC_REPLICAS: 2

services:
  kafka-1:
    image: bitnamilegacy/kafka:latest
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092"
    ports:
      - "9091:9092"

  kafka-2:
    image: bitnamilegacy/kafka:latest
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092"
    ports:
      - "9092:9092"

  kafka-3:
    image: bitnamilegacy/kafka:latest
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9092"
    ports:
      - "9093:9092"

  kafka-4:
    image: bitnamilegacy/kafka:latest
    environment:
      <<: *kafka-env
      KAFKA_CFG_NODE_ID: 4
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-4:9092"
    ports:
      - "9094:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "lab-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092,kafka-4:9092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-4


  producer-raw-data:
    build: ./backend
    command: ["python", "-m", "producers.raw_data_producer"]
    volumes:
      - "./data:/backend/data"

  producer-checkout:
    build: ./backend
    command: ["python", "-m", "producers.checkout_producer"]
    volumes:
      - "./data:/backend/data"


  ml-worker-1:
    build: ./backend
    command: ["python", "-m", "consumers.ml_worker"]
    volumes:
      - "./models:/backend/models"

  ml-worker-2:
    build: ./backend
    command: ["python", "-m", "consumers.ml_worker"]
    volumes:
      - "./models:/backend/models"

  ml-worker-3:
    build: ./backend
    command: ["python", "-m", "consumers.ml_worker"]
    volumes:
      - "./models:/backend/models"


  promo-worker:
    build: ./backend
    command: ["python", "-m", "consumers.promo_worker"]

  streamlit-ui:
    build: ./app
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"

  sandbox:
    build: ./analyze
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    ports:
      - "8888:8888"
    volumes:
      - "./models:/workspace/models"
      - "./data:/workspace/data"
